name: Compile & relese PDF on push to master

on:
  push:
    branches:    
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Github Action for LaTeX
        # You may pin to the exact commit or the version.
        # uses: xu-cheng/latex-action@cb1ec5785b7605cd308b962e0678cdcfd2595cb7
        uses: xu-cheng/latex-action@v2
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex
      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDF
      #     path: main.pdf
      - name: Rename file 
        run: export FILE_NAME=praca_`date +'%Y_%m_%d_%H:%M'`.pdf |
             echo "::set-env name=FILE_NAME::$FILE_NAME"
             mv main.pdf $FILE_NAME
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: $FILE_NAME
          artifacts: $FILE_NAME
        
